config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  mount ResqueWeb::Engine => '/resque'

  namespace :api do
    namespace :v1 do
      resources :contacts, only: [:show, :create] do
        member { post :add, :ignore }
      end

      resources :suggestions, only: [:index] do
        collection { post :recommend }
      end

      resources :notifications, only: [:show] do
        member { post :add, :ignore }
      end

      resources :subscriptions, only: [:index] do
        collection { post :unsubscribe, :subscribe }
      end
    end
  end

  namespace :admin do
    resources :owners, only: [:index, :show] do
      member { post :recalculate, :update_contacts, :fake_notification }
    end

    resources :contacts, only: [:index, :show] do
      member { post :recalculate, :update_info }
    end

    resources :notifications, only: [:index, :show]

    resources :danger_zone, only: [] do
      member { post :drop_contacts, :drop_notifications, :clear_statuses, :mark_as_friend_randomly }
    end

    resources :settings, only: [:index, :create] do
      collection { delete :index }
    end

    root to: 'dashboard#index'
  end

  resources :web_client, path: 'w', only: [:show] do
    member do
      get :add, :ignore, :unsubscribe, :subscribe
      post :add_another, :ignore_another
      get :track_email, to: 'web_client/track_emails#index'
    end
  end

  resources :documentation, only: [:show]

  root to: 'documentation#show', id: 'api'

  get 'status', to: Proc.new { [200, {}, ['']] }
end

app/views/layouts/admin/_flash.html.slim
- [:alert, :notice].each do |type|
  - if flash[type]
    .alert.alert-dismissible class=('alert-danger' if type == :alert) class=('alert-success' if type == :notice)
      button.close data-dismiss='alert' aria-label='Close'
        span aria-hidden=true &times;
      = flash[type]

app/views/layouts/admin/_menu.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      a.navbar-brand href='/admin' == "#{AppConfig.app_name} v.#{AppConfig.version}"
    ul.nav.navbar-nav
      li = link_to 'Owners', admin_owners_path
      li = link_to 'Contacts', admin_contacts_path
      li = link_to 'Notifications', admin_notifications_path
      li = link_to 'Settings', admin_settings_path
      li = link_to 'Resque', '/resque', target: '_blank'
    ul.nav.navbar-nav.navbar-right
      li = Rails.env