config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  mount ResqueWeb::Engine => '/resque'

  namespace :api do
    namespace :v1 do
      resources :contacts, only: [:show, :create] do
        member { post :add, :ignore }
      end

      resources :suggestions, only: [:index] do
        collection { post :recommend }
      end

      resources :notifications, only: [:show] do
        member { post :add, :ignore }
      end

      resources :subscriptions, only: [:index] do
        collection { post :unsubscribe, :subscribe }
      end
    end
  end

  namespace :admin do
    resources :owners, only: [:index, :show] do
      member { post :recalculate, :update_contacts, :fake_notification }
    end

    resources :contacts, only: [:index, :show] do
      member { post :recalculate, :update_info }
    end

    resources :notifications, only: [:index, :show]

    resources :danger_zone, only: [] do
      member { post :drop_contacts, :drop_notifications, :clear_statuses, :mark_as_friend_randomly }
    end

    resources :settings, only: [:index, :create] do
      collection { delete :index }
    end

    root to: 'dashboard#index'
  end

  resources :web_client, path: 'w', only: [:show] do
    member do
      get :add, :ignore, :unsubscribe, :subscribe
      post :add_another, :ignore_another
      get :track_email, to: 'web_client/track_emails#index'
    end
  end

  resources :documentation, only: [:show]

  root to: 'documentation#show', id: 'api'

  get 'status', to: Proc.new { [200, {}, ['']] }
end

app/controllers/web_client/track_emails_controller.rb
class WebClient::TrackEmailsController < ActionController::Base
  def index
    WebClient::TrackEmail.new(params).do
    send_file(Rails.root.join('public', 'email', 'track_email.gif'), type: 'image/gif', disposition: 'inline')
  end
end

app/controllers/web_client_controller.rb
class WebClientController < ApplicationController
  before_action :set_web_client
  before_action :set_contact, only: [:add_another, :ignore_another]

  def show
    @web_client = WebClientDecorator.decorate(@web_client)
    @notice = WebClient::ActionHandler::NoticeBuilder.deserialize(flash[:notice]) if flash[:notice]
  end

  def add
    handle_action(:add)
  end

  def ignore
    handle_action(:ignore)
  end

  def unsubscribe
    handle_action(:unsubscribe)
  end

  def subscribe
    handle_action(:subscribe)
  end

  def add_another
    handle_action(:add, @contact)
  end

  def ignore_another
    handle_action(:ignore, @contact)
  end

  private

  def handle_action(*args)
    @web_client.send(*args)
    secure_redirect_to(web_client_path, notice: @web_client.notice)
  end

  def set_web_client
    @web_client = WebClient::ActionHandler.new(params[:id], caller: :web_client)
    raise WebClient::NotFound unless @web_client.valid?
  end

  def set_contact
    @contact = @web_client.owner.contacts.find(params[:contact_id])
  end
end

app/views/web_client/_another_contacts.html.slim
.ff-contacts.row
  h2.title.col-xs-12 Add others on Zazo:
  - @web_client.another_contacts.each do |contact|
    - 5.times do
      .contact-wrapper.col-sm-3
        .contact
          .info-block
            .icon
              = image_tag('web_client/placeholders/1.png')
              .initials AH
            .name = contact.display_name
            .subtitle 000 000 00 00
          = link_to 'ADD', add_another_web_client_path(@web_client.nkey, contact_id: contact.id), method: :post, class: 'add-link'

app/views/web_client/_contacts.html.slim
.ff-contacts.row
  h2.title.col-xs-12 Add on Zazo:
  - @web_client.others_contacts.each do |contact|
    .contact-wrapper.col-md-3.col-sm-4.col-xs-12
      .contact
        .info-block
          .icon
            = @web_client.contact_placeholder
            .initials = contact.initials
          .name = contact.display_name
        = link_to 'ADD', add_another_web_client_path(@web_client.notification.nkey, contact_id: contact.id), method: :post, class: 'action-link add-link'
        = link_to 'IGNORE', ignore_another_web_client_path(@web_client.notification.nkey, contact_id: contact.id), method: :post, class: 'action-link remove-link'

app/views/web_client/_notification.html.slim
#notification.ff-notification-wrapper
  .ff-notification.alert.alert-info role='alert' data-notify='container'
    .icon class="#{notice.status}"
      - if %w(unsubscribed subscribed).include?(notice.status)
        = web_client.send("#{notice.status}_placeholder")
      - else
        = web_client.contact_placeholder
        .initials = web_client.contact.initials
    .text
      h3.contact-name = notice.title
      p.description = notice.description
    .action = web_client.action_link(notice.status)

app/views/web_client/show.html.slim
- if @notice
  - content_for(:outside_of_container) { render partial: 'notification',
                                                locals: { notice: @notice, web_client: @web_client } }

== render 'contacts'